const fs = require('fs');
const { desc, task } = require('jake');

task('default', runList);

desc('list js files and symlinks');
task('list', runList);

desc('create symbolic links at target directory');
task('link', ['list'], runLink);

function runList() {
  const results = returnLinkNames();

  results.forEach(([jsFile, symlink]) => console.log(`${jsFile} -> ${symlink}`));
}

function runLink() {
  const filePairs = returnLinkNames();
  const targetDir = '../../bin';

  for (let index = 0; index < filePairs.length; index += 1) {
    let [jsFile, symlink] = filePairs[index];
    let target = [__dirname, jsFile].join('/');
    let path = [targetDir, symlink].join('/');
    try {
      fs.symlinkSync(target, path);
    } catch(error) {
      if (error.code === 'EEXIST') {
        fs.unlinkSync(path);
        fs.symlinkSync(target, path);
      } else {
        throw error;
      }
    }
  }

  console.log("\x1b[32mLinks successfully created!\x1b[00m");
}

function createLinkName(jsFileName) {
  const linkName = jsFileName
    .split('.')
    .at(0)
    .split('')
    .map((letter) => (
      letter === letter.toUpperCase() ? '-' + letter.toLowerCase() : letter
    ))
    .join('');

  return linkName;
}

function returnLinkNames() {
  const listedLinks = getListedLinks();
  const jsFiles = getJsFiles();
  const linkMatrix = listedLinks
    .trim()
    .split('\n')
    .map((name) => name.split(':'));
  const linkedJsFiles = [];
  const resultingLinks = [];

  linkMatrix.forEach(([file, symlink]) => {
    linkedJsFiles.push(file);
    resultingLinks.push(symlink);
  });

  const result = [];
  for (let index = 0; index < jsFiles.length; index += 1) {
    const fileName = jsFiles[index];
    const fileIndex = linkedJsFiles.indexOf(fileName);
    let linkName;

    if (fileIndex !== -1) {
      linkName = resultingLinks[fileIndex];
    } else {
      linkName = createLinkName(fileName);
    }

    result.push([fileName, linkName]);
  }

  return result;
}

function getJsFiles() {
  return fs.readdirSync('.')
    .filter((filename) => /\.(js|cjs|mjs)$/.test(filename));
}

function getListedLinks() {
  let result;
  try {
    result = fs.readFileSync('links.txt', { encoding: 'utf-8' });
  } catch {
    result = '';
  }
  return result;
}
